---
  - name: installing and launching filebeat
    hosts: webservers
    become: yes
    tasks:

    - name: download filebeat deb
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb 
 
    - name: install filebeat deb
      command: dpkg -i metricbeat-7.6.1-amd64.deb

    - name: drop in filebeat.yml 
      copy:
       src: ./metricbeat.yml
       dest: /etc/metricbeat/metricbeat.yml

    - name: enable and configure system module
      command: metricbeat modules enable docker

    - name: metricbeat setup
      command: metricbeat setup

    - name: service metricbeat start
      command: service metricbeat start